[project]
name = "riscos-conv"
version = "0.0.1"
authors = [
  { name="Paul Stone" }
]
description = "Library and CLI tools to convert to/from RISC OS formats"
readme = "README.md"
requires-python = ">=3.13"
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.13",
  "Operating System :: OS Independent",
  "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
  "Environment :: Console",
]
dependencies = [
  "pillow",
  "pycdlib==1.21.0" # fixed due to monkey-patching
]

[project.scripts]
riscos-conv = "riscosconv.cli:cli"

[project.urls]
Homepage = "https://github.com/pdjstone/riscos-conv"
Issues = "https://github.com/pdjstone/riscos-conv/issues"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"



[project.optional-dependencies]
test = ["pytest"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src", "tests"]
